Add ability to skip updates (i.e., only do new inserts)
wizaplace/php-etl pull request #41
Opened 2020-10-17 04:17 UTC by kdebisschop

Add ability to skip updates (i.e., only do new inserts) in InsertUpdate Loader.

2020-10-18 08:27 UTC, ecourtial commented
Hi @kdebisschop and thank you for your contribution. Is it possible to update the unit test?

2020-10-19 05:40 UTC, kdebisschop commented
Unit tests added to verify update is inhibited as expected when doUpdate is false, and to confirm inserts still occur.

2020-10-19 09:45 UTC, ecourtial requested changes
Just remove the empty lines. Otherwise fine for me. 
The issue with PHPStan seems not to be related to your work :)

2020-10-19 09:45 UTC, ecourtial commented on tests/Loaders/InsertUpdateTest.php
> +
Can you remove those empty lines ?

2020-10-19 12:49 UTC, kdebisschop commented
1) fixed.
2) Yes. That PHPStan fail exists in master.

2020-10-19 15:02 UTC, ecourtial approved these changes

2020-10-19 19:09 UTC, Nicolas-Masson-Wizaplace commented on src/Loaders/InsertUpdate.php
> +            if ($this->doUpdates) {
Hello, thanks for the PR :)
Maybe we can do this in one statement instead of nested conditions ?
```suggestion
         if (
             false !== $current
             && true === $this->doUpdates
         ) {
```

2020-10-19 19:54 UTC, kdebisschop commented on src/Loaders/InsertUpdate.php
> +            if ($this->doUpdates) {
Ummm - no. That is a different logic. That would cause the row to be inserted rather than skipped.

I pushed an additional check in the test code so it you want you can try the change on a local checkout and see why it fails.

2020-10-19 21:10 UTC, Nicolas-Masson-Wizaplace commented on src/Loaders/InsertUpdate.php
> +            if ($this->doUpdates) {
oh right, got it. I have some suggestion to make this more intuitive

only check for `$current` here
```php
        ...
        $current = $this->select->fetch();

        if (false === $current) {
            $this->insert($row);
        } else {
            $this->update($row, $current);
        }
```
and do the skip in the `update` method
```php
    protected function update(array $row, array $current): void
    {
        if (false === $this->doUpdates) {
            return;
        }
        ...
```
What do you think ?

2020-10-19 23:42 UTC, kdebisschop commented on src/Loaders/InsertUpdate.php
> +            if ($this->doUpdates) {
I think that would work (and the modified test should help verify)

It does mean that your fork will be more out of sync with the original work, but it seems like that is not a concern for you. I'll try the change out.

2020-10-20 07:01 UTC, ecourtial commented on src/Loaders/InsertUpdate.php
> +            if ($this->doUpdates) {
@kdebisschop yes our fork it totally decoupled from the original work since this one has too much drawbacks (for instance the hard coupling with Laravel).

2020-10-21 08:16 UTC, Nicolas-Masson-Wizaplace approved these changes

2020-10-21 08:20 UTC, ecourtial approved these changes

2020-10-21 08:21 UTC, merged