Use Extractor to create a date dimension table.
wizaplace/php-etl pull request #43
Opened 2020-10-17 05:21 UTC by kdebisschop

I looked around for scripts to create a Date Dimension table for our warehouse and they were all way more complex and platform specific than they needed to be. Thinking of it as an extractor allowed me to implement in a fairly small number of lines of code, and to actually create the table becomes a trivial ETL.

I intentionally left holidays and fiscal periods out of the Extraction since they vary from country to country and company to company. I expect holidays and fiscal would either be implemented as Transform or would be entered into the resulting Date Dimension table manually. The manual option is made more practical with the option in #41 which adds an option to InsertUpdate to only add new rows and not overwrite them.

2020-10-18 08:39 UTC, ecourtial requested changes
Some typos. 
Interesting feature, I am going to try it.

2020-10-18 08:39 UTC, ecourtial commented on docs/Extractors/DateDimension.md
> +$etl->extract('date_demension', $iterable, $options);
dimension

2020-10-18 08:39 UTC, ecourtial commented on docs/Extractors/DateDimension.md
> +First day in date dimesnion table.
dimension

2020-10-18 08:39 UTC, ecourtial commented on docs/Extractors/DateDimension.md
> +First day in date dimesnion table.
Last day ?
dimension

2020-10-19 05:47 UTC, kdebisschop commented
Thanks for picking up those typos.

2020-10-19 09:51 UTC, ecourtial approved these changes

2020-10-19 20:25 UTC, Nicolas-Masson-Wizaplace reviewed
Nice work !

(Some cosmetic suggestion)

2020-10-19 20:25 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +            $date->add($interval);
```suggestion
```

2020-10-19 20:25 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +        $interval = new \DateInterval('P1D');
```suggestion
```

2020-10-20 00:45 UTC, kdebisschop commented on src/Extractors/DateDimension.php
> +            $date->add($interval);
I totally do not understand what you are suggesting. It causes the test to fail. The things you are suggesting I remove are precisely the parts that cause the loop to iterate forward.

Maybe moving the date incrementor to the end of the loop will make that clearer. I did that and accepted the php-cs-fixer recommendation to use yoda-style conditionals in that class also.

2020-10-20 06:58 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +            $date->add($interval);
Sorry, i think i forgot to post the last part of my suggestion :(
- moving the incrementor after the `yield` (like you guessed),
- passing the `Interval` directly as an argument to the `add` method instead of using `$interval` variable at the top.

2020-10-20 07:17 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +            // Add one day to set up the next iteraion of the loop.
Little typo
```suggestion
            // Add one day to set up the next iteration of the loop.
```

2020-10-20 14:22 UTC, kdebisschop commented on src/Extractors/DateDimension.php
> +            $date->add($interval);
Move interval calculation inside the loop causes the same value to be recalculated on every iteration. It would not slow this down a lot, possibly not even noticeably. But I would still generally consider it to be bad style. I will change it if you insist, but for now I have not changed it.

Thanks for picking up that typo - inexplicably the spell check in my IDE had gotten disabled (along with a number of other settings).

Oh - and also I realized that the test had no @copyright or @author. I added that, modeled off the header in the other files. (In fact, I'm not clear on whether I should be included as an author since I wrote it or if Leonardo Marquine should be included as copyright for code he has apparently never even seen. So I just added something to be consistent.)

2020-10-21 08:14 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +            $date->add($interval);
> Move interval calculation inside the loop causes the same value to be recalculated on every iteration. It would not slow this down a lot, possibly not even noticeably. But I would still generally consider it to be bad style. I will change it if you insist, but for now I have not changed it.
That's legit, nice work

2020-10-21 08:15 UTC, Nicolas-Masson-Wizaplace approved these changes

2020-10-21 08:18 UTC, ecourtial approved these changes

2020-10-21 08:18 UTC, merged