Use dist forms of quality tool configs consistently
wizaplace/php-etl pull request #49
Opened 2020-11-16 15:07 UTC by kdebisschop

This diff makes use of quality tools a bit more uniform and standardized, and makes minor fixes to a smal lnumber of files so code complies with the php-cs-fixer profile in the repository (tests, however, are still rather far from overall compliance).

2020-11-19 14:05 UTC, kdebisschop commented
Commit 7aae27f treis to correctly handle php extensions -- for require-dev, some are needed to run tests; all the suggestable extensions I was able to find are now suggested. Since an ETL process could be defined for CSV to CSV for instance, none ra actually truly required, I think -- even though some are required for unit tests.

2020-11-24 14:37 UTC, ecourtial approved these changes

2020-11-24 14:55 UTC, AurelienRasselet requested changes

2020-11-24 14:55 UTC, AurelienRasselet commented on src/Etl.php
> +     * @param array $options
Since you removed phpdoc type hinting for other array, why keeping this one?

2020-11-24 20:25 UTC, kdebisschop commented on src/Etl.php
> +     * @param array $options
The short answer is that I was trying to get to a level of consistency between the code and the inspection profiles in the repo that would allow a pre-commit hook to pass. But consistency within the code base itself is also a definite virtue -- let me take another look here...

2020-11-24 20:42 UTC, kdebisschop commented on src/Etl.php
> +     * @param array $options
In .php_cs, the setting 

```
  '@Symfony' => true,
```

enables
```
    'no_superfluous_phpdoc_tags' => false
```

which thus requires removing "@param string $output" or adding a variable comment. Removing the hinting in the PHPdoc was the minimal change.

I could have added array as an enforced type on the $options argument and dropped them both but there is a small chance that would cause working code to fail because of the enforced type. So I took the minimal change that would allow the code to pass the inspection profile shipped with the code.

In truth, I think a better way forward once the code and the inspection profiles are consistent is to beef up the PHPdoc and use that to generate documentation, as opposed to the current strategy of keeping them separate (which means we cannot really use code inspection to ensure the docs are accurate). To do that, we'd add to .php_cs.dist something like 

```
$phpDocRules = [
    'phpdoc_annotation_without_dot' => false,
    'no_superfluous_phpdoc_tags' => false,
    'phpdoc_align' => false,
];
```

and use phpDocumentor to generate docs equivalent to the current ones.

But it seemed the most reasonable first step was to try to formulate a minimal change that allows the code to pass the existing profiles.

I'm happy to take a different direction though.

2020-11-24 21:05 UTC, AurelienRasselet commented on src/Etl.php
> +     * @param array $options
Thanks for the explanation! It makes sense, I'll approve the PR.

I'm not sure if it's a good idea to PHPdoc everything though. It's useful for making quick and up to date documentation, and it's something I've seen in some projects, but it also make a lot of redondant comments.

I'd prefer to just have every array fully type hinted with PHPDoc (with @param string[] $options or @param mixed[] $options at least for example).
@ecourtial ?

2020-11-24 21:05 UTC, AurelienRasselet approved these changes

2020-11-24 21:35 UTC, kdebisschop commented on src/Etl.php
> +     * @param array $options
Thanks, @AurelienRasselet  -- I hear you with respect to PHPDoc having a lot of redundant comments - I've seen that too.

I think if you want PHPdoc type hints, the settings for php_cs_fixer will need to change. If that's the direction people want to take, I'm happy to build another PR for that once there is consensus and the code is in a place where the quality profile can be applied to verify compliance.

2020-11-25 12:40 UTC, ecourtial commented
@kdebisschop I merge.
Regarding you last comment 
```
I think if you want PHPdoc type hints, the settings for php_cs_fixer will need to change. If that's the direction people want to take, I'm happy to build another PR for that once there is consensus and the code is in a place where the quality profile can be applied to verify compliance.
```
Yes ! Let's discuss about this. You can open an issue to centralize all the talks about it :)

2020-11-25 12:42 UTC, merged