Add a Transformer to format a Unix timestamp as a human-readable string.
wizaplace/php-etl pull request #61
Opened 2020-11-29 02:07 UTC by kdebisschop

Resolves #58

2020-11-29 11:14 UTC, ecourtial requested changes
Two small issues in the doc

2020-11-29 11:14 UTC, ecourtial commented on src/Transformers/FormatUnixTime.php
> + * @file
Little glitch here :)

2020-11-29 11:14 UTC, ecourtial commented on tests/Transformers/FormatUnixTimeTest.php
> + * @copyright   Copyright (c) Leonardo Marquine
The contribution comes from the original project ?

2020-11-29 12:58 UTC, kdebisschop commented on src/Transformers/FormatUnixTime.php
> + * @file
Fix pushed. Thanks.

2020-11-29 12:58 UTC, kdebisschop commented on tests/Transformers/FormatUnixTimeTest.php
> + * @copyright   Copyright (c) Leonardo Marquine
Fix pushed. Thanks.

2020-11-29 15:32 UTC, ecourtial approved these changes

2020-11-30 10:40 UTC, Nicolas-Masson-Wizaplace approved these changes

2020-12-02 07:14 UTC, merged