Add callback transformer
wizaplace/php-etl pull request #63
Opened 2020-11-29 06:19 UTC by kdebisschop

Resolves issue #37

2020-11-29 10:59 UTC, ecourtial requested changes
A small question

2020-11-29 10:59 UTC, ecourtial commented on src/Transformers/Callback.php
> +     * @var string
Isn't it supposed to be a callable ?

2020-11-29 13:01 UTC, kdebisschop commented on src/Transformers/Callback.php
> +     * @var string
Spot on. Fix pushed. Thanks.

2020-11-29 15:31 UTC, ecourtial approved these changes

2020-11-29 17:18 UTC, AurelienRasselet approved these changes

2020-11-30 10:33 UTC, Nicolas-Masson-Wizaplace approved these changes

2020-12-01 14:13 UTC, kdebisschop commented
Hey all -- I may have resolved the signed commit issue (I did not realize I was missing that aspect)

I suspect, however, if I was to for instance reword the last commit and force-push the same code, it would trigger a new review requirement. But I could do that if it would help on your end. LMK if I should, otherwise I will leave as-is.

2020-12-02 07:25 UTC, ecourtial commented
@kdebisschop Not an issue with the signed commit :) We will consider that later (for all the contributors), if really needed or not.
We merge this PR. 
I would like to wait to have the full support for PHP8 before tagging the new version.

2020-12-02 07:25 UTC, merged