Use php74 property type hints
wizaplace/php-etl pull request #71
Opened 2020-12-23 15:01 UTC by kdebisschop

This a large backward-compatibility breaking patch proposal to start work on a v2 release.

2020-12-23 15:12 UTC, kdebisschop commented on .php_cs.dist
> -return PhpCsFixer\Config::create()
Config::create() is deprecated

2020-12-23 15:13 UTC, kdebisschop commented on docs/Extractors/Aggregator.md
> -$mergedData = (new Etl())
Resolves scanner complaint about using a value from a null return

2020-12-23 15:16 UTC, kdebisschop commented on src/Database/Statement.php
> -use PDO;
Most places we directly reference the top-level namespace. So let's be consistent.

2020-12-23 15:17 UTC, kdebisschop commented on src/Database/Statement.php
> -    public function prepare(): \PDOStatement
This return type was actually incorrect - if SQL is not valid, false is returned.

2020-12-25 10:11 UTC, ecourtial commented
Nice PR ! We are going to check it in details next week :)

2021-01-04 19:52 UTC, ecourtial requested changes
Some questions.

2021-01-04 19:52 UTC, ecourtial commented on .circleci/config.yml
>  version: '2.1'
We need PHPStan and PHPCs for the lowest version

2021-01-04 19:52 UTC, ecourtial commented on docs/Extractors/Collection.md
> + * @var \Wizaplace\Etl\Extractors\Collection $collection
Should we consider discussing the matter of keeping that in one line ? What is involved ?

2021-01-04 19:52 UTC, ecourtial commented on phpcs.xml.dist
> +    <rule ref="Squiz.NamingConventions.ValidVariableName">
If I understand, it is to prevent such old "pre-PSR" behaviors ?
`$_private;`
`$private_var;`

2021-01-05 13:22 UTC, kdebisschop commented on docs/Extractors/Collection.md
> + * @var \Wizaplace\Etl\Extractors\Collection $collection
Personally, I prefer the one-line form. If we had a coding style document that said using one-line was desirable, It's a pretty simple change. But since we don't, the closest we have is invoking Symfony in .php_cs.dist, and Symfony says 1-line is not allowed. In other words, I only made the change so we would have one consistent coding style.

Te symfony directive is "Don’t inline PHPDoc blocks, even when they contain just one tag (e.g. don’t put /** {@inheritdoc} */ in a single line);" at https://symfony.com/doc/current/contributing/code/standards.html

It's probably easiest to say "We follow Symfony" but if we want to say "We follow Symfony with the exception that single-line PHPdoc may (or should?) be inlined" I could update the patch.

2021-01-05 13:24 UTC, kdebisschop commented on phpcs.xml.dist
> +    <rule ref="Squiz.NamingConventions.ValidVariableName">
Exactly -- I did a count and the majority of our local variables were camel case. I made it so all were and added the phpcs directive to ensure that consistency going forward.

2021-01-05 13:27 UTC, kdebisschop commented on .circleci/config.yml
>  version: '2.1'
I don't understand your comment on a line that is not changing. Can you explain a bit more what your getting at?

2021-01-06 17:53 UTC, Nicolas-Masson-Wizaplace commented on src/Database/Statement.php
> -    public function prepare(): \PDOStatement
I wonder if it was intentional ? if we wanted this `prepare()` method to return only proper `PDOStatement` and never go further if not. (But maybe there is more explicit way to do this)

Without this type hint we will have to handle this error later in the process, and every classes that make use of this method need to know what to do with `false`.

2021-01-06 17:55 UTC, Nicolas-Masson-Wizaplace commented on src/Database/Statement.php
> -    public function prepare(): \PDOStatement
(@ecourtial maybe we need to think about using Doctrine DBAL or whatever dependency to not having to maintain such a class ?)

2021-01-06 18:02 UTC, Nicolas-Masson-Wizaplace commented on src/Database/Transaction.php
> +        return !$this->open && (0 === $this->size || 1 === $this->count);
Eventually for visual peope like me that are bad at reading inline logical :)
```suggestion
        return (
            false === $this->open
            && (
                0 === $this->size
                || 1 === $this->count
            )
        );
```

2021-01-06 18:14 UTC, ecourtial commented on docs/Extractors/Collection.md
> + * @var \Wizaplace\Etl\Extractors\Collection $collection
>Personally, I prefer the one-line form

We do that in our company too. So yes, let's ignore this Symfony rule then :)

2021-01-06 18:38 UTC, ecourtial commented on src/Database/Statement.php
> -    public function prepare(): \PDOStatement
>I wonder if it was intentional ? if we wanted this prepare() method to return only proper PDOStatement and never go further if not. (But maybe there is more explicit way to do this)

That's a good point yes. If the test passes it means that this use case was never expected I guess. I think we could keep the PDO return type.

>maybe we need to think about using Doctrine DBAL or whatever dependency to not having to maintain such a class ?)

Yes. Arthur already mentioned that in the early stage of the fork: #2 .
We could consider it. I am not a fan of adding extra dependencies, but it could make the code cleaner, more testable, we just need to be careful with the version of the DBAL.
If we agree we that, this would be obviously done in another PR :)

2021-01-06 18:40 UTC, ecourtial commented on .circleci/config.yml
>  version: '2.1'
Sorry I did put that on the first line to mark the point on this file.
The idea is that you removed jobs for PHP 7.2 and 7.3, but you did not move the PHPCS and PHPStan jobs to the new lowest version. You can see it in your PR, these two jobs are not longer here. We need them for PHP 7.4 :)

2021-01-06 21:39 UTC, Nicolas-Masson-Wizaplace commented
Nice huge work :)

2021-01-08 12:35 UTC, kdebisschop commented on .circleci/config.yml
>  version: '2.1'
Got it. Thanks. Will fix,

2021-01-08 12:40 UTC, kdebisschop commented on docs/Extractors/Collection.md
> + * @var \Wizaplace\Etl\Extractors\Collection $collection
Great. I propose adding CONTRIBUTING.md as a place to document our preferred practice - especially here where we're making a decision that does not have an inspection to enforce it.

2021-01-08 12:44 UTC, kdebisschop commented on docs/Extractors/Collection.md
> + * @var \Wizaplace\Etl\Extractors\Collection $collection
Question: inline one-line tags or inline all one-line PHPDoc?

2021-01-08 15:38 UTC, kdebisschop commented on src/Database/Statement.php
> -    public function prepare(): \PDOStatement
I'm open to a different DBAL as part of a different PR.

I also get the about seeing the error here and not letting it propagate - that's a good point. I ended up going back to the enforced type, but throwing an exception if the SQL cannot be prepared. So instead of a confusing "TypeError" exception you would get an SQL error message in an exception that would include some info about the source of the error.

2021-01-08 15:38 UTC, kdebisschop commented on .circleci/config.yml
>  version: '2.1'
Restored those two and added php-cs-fixer

2021-01-08 15:40 UTC, kdebisschop commented on docs/Extractors/Collection.md
> + * @var \Wizaplace\Etl\Extractors\Collection $collection
Added CONTRIBUTING.md, waiting on resolution of whether we want this to apply to one-line comments or just one-line annotations/tags...

2021-01-08 15:54 UTC, kdebisschop commented on src/Database/Transaction.php
> +        return !$this->open && (0 === $this->size || 1 === $this->count);
Hmmm - I'm not even 100% sure that code is doing what what is expected. At least based on tests, nothing changes if we make it 

`return !$this->open && 1 === $this->count;`

So either tests are not actually covering that functionality or some of that code is superfluous.

I'm going to leave that whole question for a different issue.

2021-01-08 17:10 UTC, kdebisschop commented on src/Database/Statement.php
> -    public function prepare(): \PDOStatement
Oh - and I added a test for the case where SQL cannot be parsed (the trick to that test is mock do not evaluate the code, so you need to connect a database (e.g., Sqllite which we already use in another test) and use that to prepare the statement.

2021-01-08 20:45 UTC, kdebisschop commented on src/Database/Transaction.php
> +        return !$this->open && (0 === $this->size || 1 === $this->count);
I created #76 so we don't lose this as a genuine concern.

2021-01-10 20:35 UTC, leNEKO approved these changes

2021-01-10 21:48 UTC, Nicolas-Masson-Wizaplace approved these changes

2021-01-12 14:01 UTC, kdebisschop commented on .circleci/config.yml
>  version: '2.1'
Fixed

2021-01-12 14:05 UTC, kdebisschop commented on docs/Extractors/Collection.md
> + * @var \Wizaplace\Etl\Extractors\Collection $collection
I have collapsed all the one-line annotations and tags. If we decide we also want to collapse one-line comments, maybe that can be a separate patch? I'm going to go ahead and mark the conversation resolved on that basis.

@ecourtial I think that all you questions have been resolved. If I missed anything, please LMK.

2021-01-12 14:06 UTC, kdebisschop commented on src/Database/Statement.php
> -    public function prepare(): \PDOStatement
Since we are bacl to just \PDOStatement as the return type, marking this as resolved also

2021-01-15 16:54 UTC, ecourtial approved these changes

2021-01-18 16:51 UTC, ecourtial commented
Need rebase :)

2021-01-20 01:19 UTC, kdebisschop commented
@ecourtial rebased

2021-02-12 14:24 UTC, ecourtial approved these changes

2021-02-12 14:24 UTC, ecourtial commented
@Nicolas-Masson-Wizaplace If it is ok for you.

2021-02-26 13:07 UTC, merged