optionnal filecounter filenames suffixes
wizaplace/php-etl pull request #72
Opened 2021-01-02 23:48 UTC by Nicolas-Masson-Wizaplace

https://github.com/wizaplace/php-etl/issues/24

2021-01-04 19:27 UTC, ecourtial requested changes
A minor question.
Aside from that, I think it will go in our next major release since it is a breaking change.

2021-01-04 19:27 UTC, ecourtial commented on src/Loaders/CsvLoader.php
> +        return "{$dirname}/{$filename}_{$this->fileCounter}.{$extension}";
We should use DIRECTORY_SEPARATOR :smile_cat:

2021-01-05 19:39 UTC, Nicolas-Masson-Wizaplace commented
> A minor question.
> Aside from that, I think it will go in our next major release since it is a breaking change.

As it will be available in a next release, i also made the filename number start @ 1 instead @ 0.

2021-01-06 14:17 UTC, kdebisschop commented on src/Loaders/CsvLoader.php
> +            return (
Parens are un-needed

2021-01-06 14:21 UTC, kdebisschop commented on src/Loaders/CsvLoader.php
> +        );
You could compose the filename in an if-else above and do something here like

`return $dirname . DIRECTORY_SEPARATOR . $file;`

That would avoid repeating the identical directory concatenation code and would solve your line length problem.

2021-01-06 14:54 UTC, kdebisschop commented on tests/Loaders/CsvLoaderTest.php
> +        [
This is sort of a nit, because this logic is quite simple ... but you have essentially copied the getFileUri() function into your test here. If there was a problem with the logic here, you'd miss it because you just copied the logic. It might be more robust to initialize class properties in setUp() for $path, $basename, and $extension and use them in line 125 to ensure the decomposition in getFileUri() gives back what you started with.

2021-01-06 14:55 UTC, kdebisschop reviewed
It is not something you introduced, but it seems wrong that initialize and finalize are run multiple times per step.

2021-01-06 15:21 UTC, Nicolas-Masson-Wizaplace commented
> It is not something you introduced, but it seems wrong that initialize and finalize are run multiple times per step.

Yes i agree, that's kinda hackish would need some refacto, i will give it a try

2021-01-06 16:00 UTC, Nicolas-Masson-Wizaplace commented on tests/Loaders/CsvLoaderTest.php
> +        [
Not sure of what you mean, can you illustrate with a logic problem we could miss with the current test?
It feels more that you want to unit test getFileUri() method ?

2021-01-06 16:08 UTC, Nicolas-Masson-Wizaplace commented
> It is not something you introduced, but it seems wrong that initialize and finalize are run multiple times per step.

@kdebisschop Well, looking at it, i am not sure of what we could do really differently to handle file splitting. If you have any ideas :)

2021-01-06 17:58 UTC, ecourtial commented on tests/Loaders/CsvLoaderTest.php
> +        [
As I understand it, it is because you copied in your test a part of the logic you want to test, which kinda reduce the effectiveness of the test itself.

2021-01-06 18:10 UTC, ecourtial commented
> > It is not something you introduced, but it seems wrong that initialize and finalize are run multiple times per step.
> 
> @kdebisschop Well, looking at it, i am not sure of what we could do really differently to handle file splitting. If you have any ideas :)

Are you guys refering to that: https://github.com/wizaplace/php-etl/blob/2c3b1b74f788c940e40e9bd1ac04b36d54e6889f/src/Pipeline.php#L192

Because for me, yes, the name is deceptive. Initialize let me think that the code inside this method is going to be run once. Could we consider to replace this mechanism by something like that:

`public function intialize() { ... logic run only one time: on object init}`
`public function atEach() { ... logic run at each pass in this step}`

2021-01-06 21:57 UTC, Nicolas-Masson-Wizaplace commented
> > > It is not something you introduced, but it seems wrong that initialize and finalize are run multiple times per step.
> > 
> > 
> > @kdebisschop Well, looking at it, i am not sure of what we could do really differently to handle file splitting. If you have any ideas :)
> 
> Are you guys refering to that:
> 
> https://github.com/wizaplace/php-etl/blob/2c3b1b74f788c940e40e9bd1ac04b36d54e6889f/src/Pipeline.php#L192
> 
> Because for me, yes, the name is deceptive. Initialize let me think that the code inside this method is going to be run once. Could we consider to replace this mechanism by something like that:
> 
> `public function intialize() { ... logic run only one time: on object init}`
> `public function atEach() { ... logic run at each pass in this step}`
> `public function finalize() { ... logic run only one time... but when ? Current mechanism ? Or on __destruct() ? }`

Ok, that's looks like a naming problematic to me, let me try a commit :)

2021-01-07 00:13 UTC, Nicolas-Masson-Wizaplace commented on tests/Loaders/CsvLoaderTest.php
> +        [
What about testing getFileUri ? see 1f480afa14c6ca1b91a6c1dd478fa637525b7e65

2021-01-10 15:32 UTC, kdebisschop commented on src/Loaders/CsvLoader.php
> +        );
The modified code is fine, I think. And it catches and edge case that was missed before. +1 for that.

The point I was attempting to make, however, is that heavy reliance on continuation lines probably does not make the code clearer. You've actually dramatically increased the number of within-statement continuation lines.

Further, since you take up 5 lines for each of your ternary operators anyway, I think a lot of people would suggest an if-else is clearer.

I'm not calling for a change here - it is valid code. I'm just offering a 3rd-party perspective on readability.

2021-01-10 15:48 UTC, kdebisschop commented on tests/Loaders/CsvLoaderTest.php
> +        [
Fair point - as I said it was a nit. The getFileUri() function is 100% covered (not only according to PHPUnit coverage, but according to infection as well). So it really is just a personal preference to avoid repeating code from the test subject in the test when I can avoid it.

No need to change what you have from my point of view.

2021-01-10 16:00 UTC, kdebisschop commented on src/Loaders/CsvLoader.php
> +            $this->openFile();
Good! To me at least, the parent method documentation does imply that initialize() and finalize() are should not run on every row -- and that could be a problem if the CsvLoader method was extended by something else. So I do think these changes may prevent future bugs.

2021-01-10 21:17 UTC, Nicolas-Masson-Wizaplace commented on src/Loaders/CsvLoader.php
> +        );
> Further, since you take up 5 lines for each of your ternary operators anyway, I think a lot of people would suggest an if-else is clearer.

Indeed, let's use if else

2021-01-11 03:16 UTC, kdebisschop submitted a review, later dismissed
This all seems good to me. Some might find fault with using reflection to test private methods, but I'm generally not dogmatic on that point. As long as we're OK with reflection in the unit test,  then these changes should be good.

2021-01-11 22:21 UTC, Nicolas-Masson-Wizaplace commented on tests/Loaders/CsvLoaderTest.php
> +        [
Moving getFileUri to a more generic method in FilePathTrait let us getting rid of this duplicated code :) https://github.com/wizaplace/php-etl/pull/72/commits/e2aae5ca68fba9ad8ef763ce84cdb4ed9b86d401

2021-01-11 22:22 UTC, Nicolas-Masson-Wizaplace commented
> This all seems good to me. Some might find fault with using reflection to test private methods, but I'm generally not dogmatic on that point. As long as we're OK with reflection in the unit test, then these changes should be good.

I have been able to get rid of reflection with this commit https://github.com/wizaplace/php-etl/pull/72/commits/e2aae5ca68fba9ad8ef763ce84cdb4ed9b86d401

2021-01-15 16:48 UTC, ecourtial submitted a review, later dismissed

2021-01-15 16:50 UTC, ecourtial commented
Nice work :)

2021-01-18 16:52 UTC, ecourtial commented
@kdebisschop Is it ok for you ?

2021-01-20 00:41 UTC, kdebisschop submitted a review, later dismissed
Looks good to me @ecourtial

2021-02-26 13:16 UTC, merged