Option Constants
wizaplace/php-etl pull request #79
Opened 2021-01-11 00:55 UTC by Nicolas-Masson-Wizaplace

Option Class that enums available options keys

2021-01-11 07:05 UTC, kdebisschop reviewed
Overall, this creates coupling between each file and a central constants class. Is that truly desirable? Columns is ubiquitous, but many others are actually unique to to one class or a small number of classes. So the option class makes it harder to make a typo, but does not prevent me from applying one class's constant to the wrong class.

For those options that are not widely used, would it be better if their constant were defined within the class that uses them?

Then perhaps COLUMNS and a few others could be defined in the Step class (I think that coupling already exists)

2021-01-11 07:07 UTC, kdebisschop commented on docs/Extractors/DateDimension.md
> -$options = ['startDate' => '2025-01-01T06:00:00+4'];
Hmmm -- this is a pre-existing typo. I could fix it elsewhere, but I don't want to cause a conflict. It should have been "endDate" which would become "Option::END_DATE" in this work.

2021-03-01 23:35 UTC, kdebisschop commented on docs/Extractors/Json.md
> +    ]
strictly speaking, should have comma here, I think.

2021-03-01 23:35 UTC, kdebisschop commented on docs/Extractors/Table.md
> +    ]
strictly speaking, should have a comma here I think

2021-03-01 23:36 UTC, kdebisschop commented on docs/Transformers/CopyColumns.md
> +    ]
comma...

2021-03-11 07:39 UTC, ecourtial approved these changes

2021-03-12 17:20 UTC, ecourtial commented
@Nicolas-Masson-Wizaplace Small rebase needed before merge :)

2021-03-19 16:49 UTC, ecourtial commented
@Nicolas-Masson-Wizaplace weird something is broken on the Unit tests

2021-03-19 17:20 UTC, Nicolas-Masson-Wizaplace commented
> @Nicolas-Masson-Wizaplace weird something is broken on the Unit tests

I think it is a bug because of an out of date DST database for the timezone "America/New_York" i think if i just relaunch the CI it could be successful

2021-03-19 17:27 UTC, Nicolas-Masson-Wizaplace commented
> > @Nicolas-Masson-Wizaplace weird something is broken on the Unit tests
> 
> I think it is a bug because of an out of date DST database for the timezone "America/New_York" i think if i just relaunch the CI it could be successful

Well it is maybe a more global bug dealing with DST. It seems that the CI could no more be successful since the 2021/03/14
![image](https://user-images.githubusercontent.com/44770402/111819429-9e034b80-88e0-11eb-8555-33ae3ee93b60.png)

I will make a dummy PR based on master to see

2021-03-19 17:35 UTC, Nicolas-Masson-Wizaplace commented
> > > @Nicolas-Masson-Wizaplace weird something is broken on the Unit tests
> > 
> > 
> > I think it is a bug because of an out of date DST database for the timezone "America/New_York" i think if i just relaunch the CI it could be successful
> 
> Well it is maybe a more global bug dealing with DST. It seems that the CI could no more be successful since the 2021/03/14
> ![image](https://user-images.githubusercontent.com/44770402/111819429-9e034b80-88e0-11eb-8555-33ae3ee93b60.png)
> 
> I will make a dummy PR based on master to see

That's it, CI on master is KO since DST in America/New_York
@ecourtial  see https://github.com/wizaplace/php-etl/pull/85

2021-03-19 23:45 UTC, Nicolas-Masson-Wizaplace commented on tests/Extractors/DateDimensionTest.php
> +        $firstDay = new \DateTime('first day of January');
We cannot use `now` to compare with the first day of the year, as the offset is not the same with DST during the year.

2021-03-19 23:48 UTC, Nicolas-Masson-Wizaplace commented on tests/Extractors/DateDimensionTest.php
>          static::assertStringEndsWith("00:00:00$offset", $result[0]['DateFull']);
This assertion is not very solid, it will be true only as long the DST don't change for the first of January.

2021-03-20 00:04 UTC, Nicolas-Masson-Wizaplace commented
@ecourtial bug fix with the DST issue in this commit https://github.com/wizaplace/php-etl/pull/79/commits/0a93177faabdd6ff455e2685ff4c26554235ce82

2021-03-22 07:32 UTC, Nicolas-Masson-Wizaplace commented on tests/Extractors/DateDimensionTest.php
>          static::assertStringEndsWith("00:00:00$offset", $result[0]['DateFull']);
I wonder if we should remove or adapt this assertion, what do you think @kdebisschop, @ecourtial ?

2021-03-22 07:37 UTC, Nicolas-Masson-Wizaplace commented on tests/Extractors/DateDimensionTest.php
> +        $firstDay = new \DateTime('first day of January');
@kdebisschop i did lot of modification on DateDimension, i would like to have your advice on this commit if you have any time :) https://github.com/wizaplace/php-etl/pull/79/commits/0a93177faabdd6ff455e2685ff4c26554235ce82.

2021-03-23 14:38 UTC, kdebisschop requested changes

2021-03-23 14:38 UTC, kdebisschop commented on src/Extractors/DateDimension.php
> +            ->format('c');
I think we want this to be 'Y-m-d' so in regions that use calendar days we track the calendar days by default instead of the 24-hour period. I'll attach a diff for the test that I think actually tests both zones that have DST and those that do not.

2021-03-23 14:42 UTC, kdebisschop commented on src/Extractors/DateDimension.php
> +            ->format('c');
Here is that patch I mentioned - if you prefer I v=can create a different branch for you to look at or add to your branch so you can adjust...

[test-daylight-savings.patch.zip](https://github.com/wizaplace/php-etl/files/6190432/test-daylight-savings.patch.zip)

2021-03-23 20:37 UTC, Nicolas-Masson-Wizaplace commented on tests/Extractors/DateDimensionTest.php
>          }
You mean in each `new Row(...)`  ?

2021-03-23 22:48 UTC, kdebisschop commented on tests/Extractors/DateDimensionTest.php
>          }
Yes.

2021-03-23 22:52 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +            ->format('c');
I did apply the patch + made some fixes :)

2021-03-23 23:26 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +    private function getOneDayInterval(): \DateInterval
Ok, in facts, the purpose of this method is only to return a P1D DateInterval, it should never return anything else.

2021-03-23 23:28 UTC, Nicolas-Masson-Wizaplace commented on tests/Extractors/DateDimensionTest.php
>          }
here https://github.com/wizaplace/php-etl/pull/79/commits/e94e749e36fe929f857f184324bdbffc2170d1cd :)

2021-03-24 00:21 UTC, kdebisschop commented on src/Extractors/DateDimension.php
> +    private function getOneDayInterval(): \DateInterval
My thinking is that it is only used in getDatePeriod() and could be a single local variable there instead of a function call repeated twice. (Obviously that is an aesthetic difference - there will be no measurable performance difference)

It's a nit, I guess. But I still think it makes it less clear because it invites the question "where else is this function being used"

2021-03-24 00:37 UTC, kdebisschop requested changes
I think just the one change to declare visibility on the constant is required.

2021-03-24 00:37 UTC, kdebisschop commented on tests/Extractors/DateDimensionTest.php
> +    const DAY_AS_SECONDS = 24 * 60 * 60;
this should indicate visibility - private I think

2021-03-24 00:38 UTC, kdebisschop commented on src/Extractors/DateDimension.php
> +            ->format('c');
I like your fixes -- i was a bit rushed getting the patch together. Thanks.

2021-03-24 01:09 UTC, Nicolas-Masson-Wizaplace commented on src/Extractors/DateDimension.php
> +    private function getOneDayInterval(): \DateInterval
Let's remove them https://github.com/wizaplace/php-etl/pull/79/commits/f93abd8aebdd0252f341f7aa08bf98eda6eaf470

2021-03-24 02:09 UTC, kdebisschop approved these changes
Lopoks good

2021-03-26 09:53 UTC, merged